version: '3.9'

services:
  db:
    image: postgres:16-alpine
    container_name: webdevmax-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: webdevmax-backend
    restart: always
    ports:
      - "5173:5173"
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/mydb?schema=public
    depends_on:
      - db

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    container_name: webdevmax-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db-data:
